
import 'moor_database.dart';
//₂₃₄₅
class DataInfo{
  List<Oxide> oxides=[
    Oxide( name: "SiO₂", role: "gf", defRole: "gf", mass: 60.09),
    Oxide( name: "Al₂O₃", role: "s", defRole: "s", mass: 101.96),
    Oxide( name: "B₂O₃", role: "s", defRole: "s", mass: 69.62),
    Oxide( name: "Li₂O", role: "a", defRole: "a", mass: 29.88),
    Oxide( name: "Na₂O", role: "a", defRole: "a", mass: 61.98),
    Oxide( name: "K₂O", role: "a", defRole: "a", mass: 94.2),
    Oxide( name: "BeO", role: "ae", defRole: "ae", mass: 25.012),
    Oxide( name: "MgO", role: "ae", defRole: "ae", mass: 40.31),
    Oxide( name: "CaO", role: "ae", defRole: "ae", mass: 56.08),
    Oxide( name: "SrO", role: "ae", defRole: "ae", mass: 103.62),
    Oxide( name: "BaO", role: "ae", defRole: "ae", mass: 153.7),
    Oxide( name: "P₂O₅", role: "a", defRole: "a", mass: 141.94),
    Oxide( name: "TiO₂", role: "o", defRole: "o", mass: 79.866),
    Oxide( name: "ZrO", role: "o", defRole: "o", mass: 107.22),
    Oxide( name: "ZrO₂", role: "o", defRole: "o", mass: 214.44),
    Oxide( name: "V₂O₅", role: "o", defRole: "o", mass: 181.88),
    Oxide( name: "Cr₂O₃", role: "o", defRole: "o", mass: 151.99),
    Oxide( name: "MnO", role: "o", defRole: "o", mass: 70.9374),
    Oxide( name: "MnO₂", role: "o", defRole: "o", mass: 86.94),
    Oxide( name: "FeO", role: "o", defRole: "o", mass: 71.84),
    Oxide( name: "Fe₂O₃", role: "o", defRole: "o", mass: 159.69),
    Oxide( name: "CoO", role: "o", defRole: "o", mass: 74.93),
    Oxide( name: "NiO", role: "o", defRole: "o", mass: 74.6928),
    Oxide( name: "CuO", role: "o", defRole: "o", mass: 79.545),
    Oxide( name: "Cu₂O", role: "o", defRole: "o", mass: 143.09),

    Oxide( name: "CdO", role: "o", defRole: "o", mass: 128.41),
    Oxide( name: "ZnO", role: "ae", defRole: "ae", mass: 81.39),
    Oxide( name: "F", role: "o", defRole: "o", mass: 18.9984),
    Oxide( name: "PbO", role: "ae", defRole: "ae", mass: 223.2),
    Oxide( name: "SnO₂", role: "o", defRole: "o", mass: 150.7),
    Oxide( name: "HfO₂", role: "o", defRole: "o", mass: 210.49),
    Oxide( name: "Nb₂O₅", role: "o", defRole: "o", mass: 265.81),
    Oxide( name: "Ta₂O₅", role: "o", defRole: "o", mass: 441.893),
    Oxide( name: "MoO₃", role: "o", defRole: "o", mass: 143.94),
    Oxide( name: "WO₃", role: "o", defRole: "o", mass: 231.84),
    Oxide( name: "OsO₂", role: "o", defRole: "o", mass: 222.229),
    Oxide( name: "IrO₂", role: "o", defRole: "o", mass: 224.22),
    Oxide( name: "PtO₂", role: "o", defRole: "o", mass: 227.08),
    Oxide( name: "Ag₂O", role: "o", defRole: "o", mass: 231.735),
    Oxide( name: "Au₂O₃", role: "o", defRole: "o", mass: 441.931),
    Oxide( name: "GeO₂", role: "gf", defRole: "gf", mass: 104.61),
    Oxide( name: "As₂O₃", role: "o", defRole: "o", mass: 197.841),
    Oxide( name: "Sb₂O₃", role: "o", defRole: "o", mass: 291.52),
    Oxide( name: "Bi₂O₃", role: "o", defRole: "o", mass: 465.96),
    Oxide( name: "SeO₂", role: "o", defRole: "o", mass: 110.96),
    Oxide( name: "La₂O₃", role: "o", defRole: "o", mass: 325.81),
    Oxide( name: "CeO₂", role: "o", defRole: "o", mass: 172.115),
    Oxide( name: "PrO₂", role: "o", defRole: "o", mass: 172.906),
    Oxide( name: "Pr₂O₃", role: "o", defRole: "o", mass: 329.813),
    Oxide( name: "Nd₂O₃", role: "o", defRole: "o", mass: 336.48),
    Oxide( name: "U₃O₈", role: "o", defRole: "o", mass: 842.1),
    Oxide( name: "Sm₂O₃", role: "o", defRole: "o", mass: 348.72),
    Oxide( name: "Eu₂O₃", role: "o", defRole: "o", mass: 351.926),
    Oxide( name: "Tb₂O₃", role: "o", defRole: "o", mass: 365.85),
    Oxide( name: "Dy₂O₃", role: "o", defRole: "o", mass: 372.998),
    Oxide( name: "Ho₂O₃", role: "o", defRole: "o", mass: 377.859),
    Oxide( name: "Er₂O₃", role: "o", defRole: "o", mass: 382.56),
    Oxide( name: "Tm₂O₃", role: "o", defRole: "o", mass: 385.866),
    Oxide( name: "Yb₂O₃", role: "o", defRole: "o", mass: 394.08),
    Oxide( name: "Lu₂O₃", role: "o", defRole: "o", mass: 397.932),
  ];
  List<Mat> mats=[
    Mat(name: "Nepheline Syenite", lowerName: "nepheline syenite", info: "Nepheline Syenite from the East Coast ", def: true)
  ];
  List<MatOxide> matOxides=[
    MatOxide( oxideId: 1, matId: 1, count: 98.24),
    MatOxide(oxideId: 2, matId: 1, count: 0.02),
    MatOxide( oxideId: 3, matId: 1, count: 1.7),
    MatOxide( oxideId: 4, matId: 1, count: 1.7),
    MatOxide( oxideId: 5, matId: 1, count: 1.7),
  ];
  List<Folder> folders=[
    Folder( name: "Favourites", del: false),
    Folder( name: "Testing", del: false),
    Folder( name: "Drafts", del: false),
  ];
}